export "choices/choices.dart";

/// {@template openai_stream_chat_completion_usage}
/// The [OpenAIStreamChatCompletionUsageModel] class represents the usage model of the OpenAI API, which is used and get returned while using the chat methods that leverages [Stream] functionality.
/// {@endtemplate}
final class OpenAIStreamChatCompletionUsageModel {
  /// The number of tokens used for the prompt(s).
  final int promptTokens;

  /// The number of tokens used for the chat completion(s).
  final int completionTokens;

  /// The total number of tokens used for the chat completion(s).
  /// This is the sum of [promptTokens] and [completionTokens].
  final int totalTokens;

  /// Breakdown of tokens used in a completion.
  final OpenAIStreamChatCompletionCompletionTokenDetails? completionTokenDetails;

  /// Breakdown of tokens used in the prompt.
  final OpenAIStreamChatCompletionPromptTokenDetails? promptTokenDetails;

  final int? _promptCacheHitTokens;

  final int? _promptCacheMissTokens;

  /// Number of tokens in the prompt that hits the context cache.
  int? get promptCacheHitTokens => _promptCacheHitTokens ?? promptTokenDetails?.cachedTokens;

  /// Number of tokens in the prompt that misses the context cache.
  int? get promptCacheMissTokens =>
      _promptCacheMissTokens ??
      (promptTokenDetails?.cachedTokens != null
          ? promptTokens - promptTokenDetails!.cachedTokens!
          : null);

  @override
  int get hashCode {
    return promptTokens.hashCode ^
        completionTokens.hashCode ^
        totalTokens.hashCode ^
        completionTokens.hashCode;
  }

  /// {@macro openai_stream_chat_completion_usage}
  const OpenAIStreamChatCompletionUsageModel({
    required this.promptTokens,
    required this.completionTokens,
    required this.totalTokens,
    required this.completionTokenDetails,
    required this.promptTokenDetails,
    required int? promptCacheHitTokens,
    required int? promptCacheMissTokens,
  })  : _promptCacheHitTokens = promptCacheHitTokens,
        _promptCacheMissTokens = promptCacheMissTokens;

  /// {@macro openai_stream_chat_completion_usage}
  /// This is used  to convert a [Map<String, dynamic>] object to a [OpenAIStreamChatCompletionUsageModel] object.
  factory OpenAIStreamChatCompletionUsageModel.fromMap(
    Map<String, dynamic> json,
  ) {
    return OpenAIStreamChatCompletionUsageModel(
      promptTokens: json['prompt_tokens'],
      completionTokens: json['completion_tokens'],
      totalTokens: json['total_tokens'],
      completionTokenDetails: json['completion_tokens_details'] != null
          ? OpenAIStreamChatCompletionCompletionTokenDetails.fromMap(
              json['completion_tokens_details'],
            )
          : null,
      promptTokenDetails: json['prompt_tokens_details'] != null
          ? OpenAIStreamChatCompletionPromptTokenDetails.fromMap(
              json['prompt_tokens_details'],
            )
          : null,
      promptCacheHitTokens: json['prompt_cache_hit_tokens'],
      promptCacheMissTokens: json['prompt_cache_miss_tokens'],
    );
  }

  @override
  String toString() {
    return 'OpenAIChatCompletionUsageModel(promptTokens: $promptTokens, completionTokens: $completionTokens, totalTokens: $totalTokens)';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is OpenAIStreamChatCompletionUsageModel &&
        other.promptTokens == promptTokens &&
        other.completionTokens == completionTokens &&
        other.totalTokens == totalTokens;
  }
}

/// {@template openai_stream_chat_completion_completion_token_details}
/// The [OpenAIStreamChatCompletionCompletionTokenDetails] class represents
/// the breakdown of tokens used in a completion.
/// {@endtemplate}
final class OpenAIStreamChatCompletionCompletionTokenDetails {
  /// When using Predicted Outputs, the number of tokens in the prediction that
  /// appeared in the completion
  final int? acceptedPredictionTokens;

  /// Audio input tokens generated by the model.
  final int? audioTokens;

  /// Tokens generated by the model for reasoning.
  final int? reasoningTokens;

  /// When using Predicted Outputs, the number of tokens in the prediction
  /// that did not appear in the completion.
  /// However, like reasoning tokens, these tokens are still counted in the
  /// total completion tokens for purposes of billing, output,
  /// and context window limits.
  final int? rejectedPredictionTokens;

  /// Text output tokens generated by the model.
  final int? textTokens;

  @override
  int get hashCode {
    return acceptedPredictionTokens.hashCode ^
        audioTokens.hashCode ^
        rejectedPredictionTokens.hashCode ^
        textTokens.hashCode ^
        reasoningTokens.hashCode;
  }

  /// {@macro openai_stream_chat_completion_completion_token_details}
  const OpenAIStreamChatCompletionCompletionTokenDetails({
    required this.acceptedPredictionTokens,
    required this.audioTokens,
    required this.reasoningTokens,
    required this.rejectedPredictionTokens,
    required this.textTokens,
  });

  /// {@macro openai_stream_chat_completion_completion_token_details}
  /// This is used  to convert a [Map<String, dynamic>] object to a [OpenAIStreamChatCompletionCompletionTokenDetails] object.
  factory OpenAIStreamChatCompletionCompletionTokenDetails.fromMap(
    Map<String, dynamic> json,
  ) {
    return OpenAIStreamChatCompletionCompletionTokenDetails(
      acceptedPredictionTokens: json['accepted_prediction_tokens'],
      audioTokens: json['audio_tokens'],
      reasoningTokens: json['reasoning_tokens'],
      rejectedPredictionTokens: json['rejected_prediction_tokens'],
      textTokens: json['text_tokens'],
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is OpenAIStreamChatCompletionCompletionTokenDetails &&
        other.acceptedPredictionTokens == acceptedPredictionTokens &&
        other.audioTokens == audioTokens &&
        other.rejectedPredictionTokens == rejectedPredictionTokens &&
        other.textTokens == textTokens &&
        other.reasoningTokens == reasoningTokens;
  }
}

/// {@template openai_stream_chat_completion_prompt_token_details}
/// The [OpenAIStreamChatCompletionCompletionTokenDetails] class represents
/// the breakdown of tokens used in the prompt..
/// {@endtemplate}
final class OpenAIStreamChatCompletionPromptTokenDetails {
  /// Audio input tokens present in the prompt.
  final int? audioTokens;

  /// The unadjusted number of prompt tokens written to cache.
  final int? cacheWriteTokens;

  /// Cached tokens present in the prompt.
  final int? cachedTokens;

  /// Image input tokens present in the prompt.
  final int? imageTokens;

  /// Text input tokens present in the prompt.
  final int? textTokens;

  @override
  int get hashCode {
    return audioTokens.hashCode ^
        cacheWriteTokens.hashCode ^
        cachedTokens.hashCode ^
        imageTokens.hashCode ^
        textTokens.hashCode;
  }

  /// {@macro openai_stream_chat_completion_prompt_token_details}
  const OpenAIStreamChatCompletionPromptTokenDetails({
    required this.audioTokens,
    required this.cacheWriteTokens,
    required this.cachedTokens,
    required this.imageTokens,
    required this.textTokens,
  });

  /// {@macro openai_stream_chat_completion_prompt_token_details}
  /// This is used  to convert a [Map<String, dynamic>] object to a [OpenAIStreamChatCompletionPromptTokenDetails] object.
  factory OpenAIStreamChatCompletionPromptTokenDetails.fromMap(
    Map<String, dynamic> json,
  ) {
    return OpenAIStreamChatCompletionPromptTokenDetails(
      cacheWriteTokens: json['cache_write_tokens'],
      audioTokens: json['audio_tokens'],
      cachedTokens: json['cached_tokens'],
      imageTokens: json['image_tokens'],
      textTokens: json['text_tokens'],
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is OpenAIStreamChatCompletionPromptTokenDetails &&
        other.cacheWriteTokens == cacheWriteTokens &&
        other.audioTokens == audioTokens &&
        other.cachedTokens == cachedTokens &&
        other.textTokens == textTokens &&
        other.imageTokens == imageTokens;
  }
}
